# https://taskfile.dev
---
version: '3'

tasks:
  default:
    silent: true
    cmds:
      - task --list

  init:
    desc: Initialize project
    cmds:
      - uv sync --locked --all-extras --dev

  init-asdf:
    desc: Initialize project ASDF tools
    cmds:
      - cat .tool-plugins | xargs --verbose --max-lines=1 asdf plugin add
      - asdf install

  upgrade:
    desc: Upgrade project dependencies
    cmds:
      - uv lock --upgrade
      - uv sync

  format:
    desc: Format Python code
    cmds:
      - uv run ruff format

  lint:
    desc: Lint Python code
    cmds:
      - uv run mypy src
      - uv run pylint src tests

  build:
    desc: Build Python package
    cmds:
      - uv build

  test:
    desc: Test Python package
    cmds:
      - uv run pytest --durations 10

  smoke-tests:
    desc: Run smoke tests
    preconditions:
      - sh: docker run --rm --network host docker.io/redis:8 redis-cli PING
        msg: "ERROR: Redis service must be running."
    cmds:
      - uv run python tests/smoke_test_rq.py

  build-docs:
    desc: Build HTML documentation
    dir: docs
    cmds:
      - uv run sphinx-apidoc -o source/api ../src/tasktronaut
      - uv run make html

  # https://docs.astral.sh/uv/guides/package/#updating-your-version
  bump-version:
    desc: Bump Python package minor version
    preconditions:
      - sh: git diff-index --quiet HEAD --
        msg: "ERROR: Uncommitted files found."
    vars:
      CURRENT:
        sh: uv version --short
      NEXT:
        sh: uv version --bump minor --dry-run --short
    prompt: Bump Python package version from {{.CURRENT}} to {{.NEXT}}?
    cmds:
      - uv version --bump minor
      - git add pyproject.toml uv.lock
      - git commit -m "bump version"

  release:
    desc: Create a release
    preconditions:
      - sh: git diff-index --quiet HEAD --
        msg: "ERROR: Uncommitted files found."
    vars:
      GIT_SHA:
        sh: git rev-parse --short HEAD
      VERSION:
        sh: uv version --short
    prompt: Create a release for version {{.VERSION}} [{{.GIT_SHA}}]?
    cmds:
      - |
        prev=$(git describe --abbrev=0 --tags HEAD)
        git log ${prev}..HEAD --pretty=oneline --first-parent --no-decorate > .notes
      - git tag --sign --file=.notes v{{.VERSION}}
      - git push origin main --tags
      - gh release create --notes-from-tag --draft --latest v{{.VERSION}}

  redis-service:
    desc: Run Redis Service
    cmds:
      - docker run --rm -p 127.0.0.1:6379:6379 docker.io/redis:8
